language: java

addons:
  sonarcloud:
    organization: "welldoer-github"
    token:
      secure: "6c22310b31701788079f8760577fe271f7dc11e6"

cache:
  directories:
    - "$HOME/.gradle"
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

services:
  - xvfb
  
script:
  - sudo apt-get install at-spi2-core
  - ./gradlew sonarqube

after_failure:
 - cat /home/travis/build/welldoer/SWT-WarmUp-Lab/build/reports/tests/test/index.html
